version: "3.8"

services:
  ingestion:
    image: azamiue/go-ingestion:dev
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    container_name: go-ingestion-app
    network_mode: "host"
    env_file:
      - .env
    environment:
      - USR=${USR}
      - PASSWD=${PASSWD}
      - REDIS_ADDR=${REDIS_ADDR}
      - ENV=${ENV}
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
