version: "3.8"

services:
  ingestion:
    image: azamiue/go-ingestion:latest
    container_name: go-ingestion-app
    network_mode: "host"
    environment:
      - USR=${USR}
      - PASSWD=${PASSWD}
      - REDIS_ADDR=${REDIS_ADDR:-localhost:6379}
      - ENV=${ENV:-production}
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
